### ISSUE TITLE
Can't load file

### ISSUE THREAD

**Issue by tlkiong** [shakiba/svgexport#29] opened 2016-03-23 07:40 UTC
Receive the following error:

> Error: Unable to load file (fail):  the_file_name_that_is_passed_in.svg

**Comment by tlkiong** [comment] 2016-03-23 07:50
This issue is fixed on the pull request https://github.com/shakiba/svgexport/pull/30

To fix this, go to:

<path to your npm module>/svgexport/render.js

line 43:
`page.open(svgfile, function(status) {`

Change that to: 
`page.open('file:///'+svgfile, function(status) {`

However, it seems Travis CI is failing. All I did was add a few characters into the code yet the error its throwing is no environment variables check and etc.

**Comment by shakiba** [comment] 2016-03-23 23:47
Can you please share the exact code or command you are using? Meanwhile I t don't think this is good solution, because for example it does not work with relative locations or any protocol other than `file`.

**Comment by tlkiong** [comment] 2016-03-24 01:14
The exact command I used was:

`svgexport abc.svg xxx.jpg`

My OS is Windows 7. Further debug was that the protocol was unknown for "c" or "d" (depending on which drive the file is from) for abc.svg

**Comment by shakiba** [comment] 2016-03-24 01:30
I see, can you please try `./abc.svg`? I don't have access to any Windows computer right now.

**Comment by shakiba** [comment] 2016-03-24 01:32
Can I ask where the abc.svg file is located? Probably you can just use `c:\abc.svg` or `.\abc.svg` depending on where your file is located.

**Comment by tlkiong** [comment] 2016-03-24 01:58
The error shown:

`Unable to load file (fail): C:/....../abc.svg`

I have verified twice, thrice, 4 times that the path is correct.
I have also checked with phantomjs's webpage module to return statuses (errors, success and etc) during the page.open.

The error returned was:

`Invalid protocol 'c'`

**Comment by shakiba** [comment] 2016-03-24 02:11
Have you tried backslash `\` instead of forward slash `/`? That is `c:\` (not `c:/`).

**Comment by tlkiong** [comment] 2016-03-24 02:23
Seriously?
I just show you the command I use

`svgexport abc.svg xxx.jpg`

Clearly I didn't state the path. Clearly the path was inferred by your code (_dirname). It's not my choice it's a forward or backward slash.

Furthermore, windows by default is that format.

**Comment by tlkiong** [comment] 2016-03-24 02:29
The reason I chose to put 'file:///' is because that's the only protocol that is supporting opening of files from the file system by a browser. (Try opening a HTML, svg or any file in your browser. Then see the url. It'll be prefix with that 'file:///')

Your concern on whether it's a relative path or not is not really valid as I placed that code at the final section (load said file in phantomjs). All relative paths have their full paths inferred before that. The proof is that I pass in a relative path of my svg and it can still work.

**Comment by shakiba** [comment] 2016-03-24 02:47
As far as I know Windows uses backslash not forward slash, that is `c:\`.

I'm not sure why your path is not being resolved correctly, but I think it's better to fix it first.

**Comment by tlkiong** [comment] 2016-03-24 02:49
Ouch. My bad. Sorry for that. My path is in the forward slash. And I dare say it has nothing to do with the path. If the path is wrong it will fail much earlier

**Comment by shakiba** [comment] 2016-03-24 02:50
I see, so is there still any issue?

**Comment by tlkiong** [comment] 2016-03-24 02:53
Like i have been saying from the start, the path is NOT the issue here... The issue is with the latest upgrade of phantomjs that is reading 'c' (if the file path starts with (C:\)) is an invalid protocol. The path is fine. It just fails when it tries to load the path into phantomjs.

**Comment by vitalymak** [comment] 2016-03-25 16:59
On OSX 10.11.4
```
Error: Unable to load file (fail): /full/path/app-icon
```
`app-icon` without `.svg` extension. If I add `.svg` then no such error.

**Comment by Tiliavir** [comment] 2016-04-08 09:19
Same here. If I try to execute svgexport, the path is resolved perfectly fine, but it fails to open with said error:

```
PS R:\GitHub\RepoName\Documentation> svgexport test.svg test.jpg 80%
Error: Unable to load file (fail): R:\GitHub\RepoName\Documentation\test.svg
```

OS is Windows 10; svgexport executed in PowerShell.

**Comment by tlkiong** [comment] 2016-04-08 09:54
@Tiliavir follow my fix as I have shown above for now as the PR is not approved.

**Comment by Tiliavir** [comment] 2016-04-11 14:37
Thanks worked perfectly - hope to see it in the repo soon...

**Comment by ArchCodeMonkey** [comment] 2016-05-01 01:25
I was having the same problem and I have a potential fix based on the one suggested by @tlkiong but should also satisfy the concerns of @shakiba 

I found that neither relative nor absolute paths would work.
![error1](https://cloud.githubusercontent.com/assets/11328425/14939450/da295aca-0f8a-11e6-8905-f9e86f8dc913.png)
![error2](https://cloud.githubusercontent.com/assets/11328425/14939453/f5776c0e-0f8a-11e6-9f13-0ac22cf9d093.png)

I modifed `render.js` to output more information on the error.
```javascript
page.onResourceError = function(resourceError) {
   console.log('Unable to load resource (URL:' + resourceError.url + ')');
   console.log('Error code: ' + resourceError.errorCode);
   console.log('Description: ' + resourceError.errorString);
};
```
This error information indicated that @tlkiong is on the right track as PhantomJS is confused by the URI that is being given to its `open()` method. I suspect this could be an issue confined to Windows systems due to the drive letter looking like a URI protocol scheme.
![error3](https://cloud.githubusercontent.com/assets/11328425/14939459/4963f364-0f8b-11e6-8494-2accc7ea8ce8.png)

Out of interest I checked using a HTTP URI and got the same error.
![error4](https://cloud.githubusercontent.com/assets/11328425/14939469/b98ff3ae-0f8b-11e6-8431-e23ef5b76c99.png)

Based on this information I made the following change to `index.js` where it is building the command list.
*Original Code*
```javascript
    input[0] = path.resolve(cwd, input[0]);
```
*Modified Code*
```javascript
var url = require('url');
var parsedUrl = url.parse(input[0]);

if (parsedUrl.protocol !== 'http:') {
   input[0] = 'file:///' + path.resolve(cwd, input[0]);
}

```

This fix should allow the program to work with relative and absolute file paths and also open HTTP URIs.
Rerunning the tests now successfully generates the output file.
![fixed1](https://cloud.githubusercontent.com/assets/11328425/14939495/e5c5db90-0f8c-11e6-8e41-3dd3e48f0789.png)

![fixed3](https://cloud.githubusercontent.com/assets/11328425/14939517/e07eb6b0-0f8d-11e6-8355-019abd0fc410.png)

![fixed2](https://cloud.githubusercontent.com/assets/11328425/14939497/e8698b62-0f8c-11e6-8d4f-a87d207856a9.png)

**Comment by tlkiong** [comment] 2016-05-01 02:04
That was what I was thinking initially. However, at the beginning of the code where the call is made to the relative or absolute path, it is only fetching from the filesystem. This means it isn't a http URI but only can be a fs path. That's the reason for not checking whether it's a http or not as it is unnecessary.

That's my opinion though

**Comment by shakiba** [comment] 2016-05-01 03:08
I guess @tlkiong is right, currently only reading from file is supports anyway. But index.js is a better place to do the modification. I would be happy to merge it if anyone submit a PR.

This issue is also (submitted)[https://github.com/ariya/phantomjs/issues/14194] to phantomjs.

**Comment by tlkiong** [comment] 2016-05-01 03:11
The reason my PR is doing it at the final stage is to give it the code a bit of flexibility in terms of being able to do anything with the file (since we need the file path) before loading it to phantomjs. If we were to do it at index.js at the start and if in the future there would be a need for new features to enable modification of file contents, it will be a problem.

**Comment by shakiba** [comment] 2016-05-01 03:36
I see, actually I expect it to be fixed by phantomjs in future. As a short-term workaround, I think fixing it at the same place that file path is resolved would be better.

**Comment by tlkiong** [comment] 2016-05-01 03:37
I don't think there will be a "fix" by phantomjs as this is the correct way for phantomjs to handle it

It was a deliberate improvement on their part to add this in

**Comment by ArchCodeMonkey** [comment] 2016-05-01 03:39
I only suggested making a change in `index.js` for convenience as PhantomJS doesn't natively support the `url` module and that seemed to be a clean way to check if the path already referenced a protocol scheme. If you aren't worried about being able to load from HTTP then it doesn't really matter where the fix is done.

**Comment by shakiba** [comment] 2016-05-01 03:40
@tlkiong How do you know that? There is already a similar open and confirmed [issue](https://github.com/ariya/phantomjs/issues/14194).

**Comment by ArchCodeMonkey** [comment] 2016-05-01 03:56
Although, something like this would probably work in `render.js`.
```javascript
var link = document.createElement('a');
link.href = svgfile;

if (link.protocol !== 'http:') {
   svgfile = 'file:///' + svgfile;
}
```

**Comment by shakiba** [comment] 2016-05-01 08:53
I have added following temporary fix, can you please check it:
```js
    if (/^[a-z]\:\\/.test(input[0])) {
      input[0] = 'file:///' + input[0];
    }
```

**Comment by shakiba** [comment] 2016-05-03 08:09
I published a new version with the fix, please let me know if the issue is not resolved.

Thanks everyone one for reporting and other helps!

**Closed by shakiba** 2016-05-03 08:09 UTC
